### ISSUE TITLE
How to install same wireless card

### ISSUE THREAD

**Issue by zc910704** [laelsirus/GA-B360M-D3H-with-UHD630-iGPU-AMD-dGPU-CLOVER#1]
Hey guys.
I bought the same wireless card  BCM943602CS.when I intall it,the wifi works well,but the bluetooth just can't work. So How can I install your EFI  with the same BCM943602CS card?Thank you!

**Comment by zc910704** [comment]
hey ,I just come to say I found when I plug the wireless card into another usb socket. the bluetooth began to work. So I guess it maybe an usb problem,it maybe helpful for somebody who has the same comfusing like me, you can try this way. Still thank you for the EFI，it save a lot of times. ：）

**Comment by laelsirus** [comment]
Sorry I'm late! 
I confirmed your issue now. 
As you say, one internal USB 2.0 port of later indexed is disabled. (HS09 port is activated)
This forced me to disable either of them due to the USB limit patch.
Thank you for leaving issue!
