### ISSUE TITLE
black screen and network card not detected

### ISSUE THREAD

**Issue by Got99** [laelsirus/GA-B360M-D3H-with-UHD630-iGPU-AMD-dGPU-CLOVER#2]
mojave14.6(final)     8700 and d3h
I update bios and update you latest efi     ->   network card not working 
so I Reduce bios to f12    -> black screen and entwork card  problem ofter happen
what's wrong with me  ,  how to solve this problem ?
re generate dsdt and usb.aml and friendly?
      -> generate dsdt.aml with aida64 & MaciASL?
please ,thank you

**Comment by laelsirus** [comment]
When you change BIOS version, DSDT must be repatch or remove. 
For regenerating DSDT, extract and patch from your orgin DSDT.
No other SSDT needs to be regenerated by changing the BIOS version.

First, try remove dsdt. 

Which one of Bluetooth, WIFI or Ethernet does not work?
And did it boot with a black screen or did it fail to boot?

**Comment by Got99** [comment]
lan network  ,I didn't bought cs2.   
what i need to do ?
   - only dsdt need to  regenerating  
   - 4.20   or 3.1.3 which best for mojave14.6?( I need 32-bit program)

**Comment by laelsirus** [comment]
What does 4.20 or 3.1.3 mean?
Have you tried remove the DSDT?

**Comment by Got99** [comment]
Your efi  tags    the latest is 4.20   supoort catalina
I'm on working ,  I will try this evening

**Comment by laelsirus** [comment]
Sorry, I got it now.
It is recommended to try with 4.2.0
In case of Ethernet, it may be good to check whether it works well in Windows.

Try removing, regenerating DSDT and let me know the results.

**Comment by Got99** [comment]
clover version always has been 5070?
i remove dsdt ,    all is ok  now~~
regenerating DSDT with ubuntu?

**Comment by laelsirus** [comment]
Extract your origin dsdt with the clover bootloader without Ubuntu.

See this
https://www.elitemacx86.com/threads/how-to-extract-dsdt-ssdts.44/

Then decompile DSDT.aml to DSDT.asl with iasl, use the MaciASL app to patch.

iasl :
https://github.com/RehabMan/Intel-iasl.git
https://bitbucket.org/RehabMan/acpica/downloads/

Updating clover is optional. 
I recently updated the clover for macos 10.15.4

**Comment by Got99** [comment]
I download wrong. I use version 4.1.2 ,not 4.2.0

**Comment by laelsirus** [comment]
It doesn't matter. 
I release new versions when major updates or major stabilization elements are available
However, I recommend the latest release version.
