### ISSUE TITLE
what should i do when only use UHD630

### ISSUE THREAD

**Issue by skyshenfu** [laelsirus/GA-B360M-D3H-with-UHD630-iGPU-AMD-dGPU-CLOVER#4]

**Comment by laelsirus** [comment]
See the ETC entry in readme.



Intel® UHD Graphics 630

If your iGPU is 'Intel® UHD Graphics 630' and there is no AMD dGPU, use 'config_igpu.plist'
DP and HDMI ports work normally, but DVI and VGA ports have black screen after booting
